apiVersion: v1
kind: Service
metadata:
  name: tax-calculator-service
  labels:
    app: tax-calculator
spec:
  type: NodePort
  selector:
    app: tax-calculator
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
    protocol: TCP

